# Generated by Django 5.0.4 on 2024-04-21 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_hash_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('hash_value', models.CharField(max_length=100)),
                ('obfuscatedvalue', models.CharField(max_length=100)),
                ('deobfuscatdvalue', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IsActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.gender')),
                ('hash_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.file_hash_value')),
                ('isactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.isactive')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.position')),
            ],
        ),
    ]
